// Writes the chosen head (C-lr) as a versioned JSON file and the SQL that
// installs it. The JSON's SHA-256 is stored in public.moderation_models.
//   node export-head.ts <results.json> <model-id> <policy-version>
import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { VISUAL_MODEL } from '../../lib/visual-model.ts';

const [RESULTS, ID, POLICY] = process.argv.slice(2);
if (!POLICY) throw new Error('usage: node export-head.ts <results.json> <model-id> <policy-version>');
const r = JSON.parse(await readFile(RESULTS, 'utf8'))['C-lr'];
const round = (x: number) => Number(x.toPrecision(7));
const head = {
  id: ID,
  policy_version: POLICY,
  visual_model_id: VISUAL_MODEL.id,
  visual_model_sha256: VISUAL_MODEL.sha256,
  formula: 'p = sigmoid(w · x + b), x = L2-normalised DINOv2 CLS vector',
  categories: Object.fromEntries((['firearm', 'blade'] as const).map((c) => [c, {
    weights: r.head[c].w.map(round),
    bias: round(r.head[c].b),
    t_review: round(r.thresholds.review[c]),
    t_block: Number.isFinite(r.thresholds.block[c]) ? round(r.thresholds.block[c]) : null,
  }])),
};
const json = JSON.stringify(head, null, 1) + '\n';
const sha = createHash('sha256').update(json).digest('hex');
const file = path.join(import.meta.dirname, `head-${ID}.json`);
await writeFile(file, json);
const rows = Object.entries(head.categories).map(([c, h]) =>
  `  ('${ID}', '${c}', '[${h.weights.join(',')}]', ${h.bias}, ${h.t_review}, ${h.t_block ?? 'null'})`).join(',\n');
console.log(`-- generated by Web/tools/moderation-bench/export-head.ts from head-${ID}.json (sha256 ${sha})
insert into public.moderation_models (id, visual_model_id, head_sha256, policy_version, active)
values ('${ID}', '${VISUAL_MODEL.id}', '${sha}', '${POLICY}', false)
on conflict (id) do nothing;
insert into public.moderation_heads (model_id, category, weights, bias, t_review, t_block) values
${rows}
on conflict (model_id, category) do nothing;
update public.moderation_models set active = false where visual_model_id = '${VISUAL_MODEL.id}' and id <> '${ID}';
update public.moderation_models set active = true where id = '${ID}';`);
