-- ============================================================================
-- AI matching v2 — matches that actually get found, kept current, and pushed
-- exactly once.
--
-- Why (measured on the live DB, 2026-09-24):
--   * item_matches had 0 rows with 99 live listings. Matching ran ONCE, from
--     the items INSERT/approve trigger — before the client had inserted the
--     item's photos and long before generate-embedding wrote their vectors,
--     so the image signal (the strongest one) never counted, and nothing
--     re-ran it later.
--   * The image cut-off (cosine > 0.75) sat above what this embedding model
--     produces for the same object: duplicate posts of one item by one user
--     score p50 0.66; different items in the same category p50 0.53
--     (p99 0.82); different categories p50 0.35. So the image signal is now
--     graded 0.55 -> 0.80 instead of a 0.75 cliff.
--   * A "found" dated months BEFORE the "lost" still scored (all 21 current
--     candidate pairs are like that). Finding something before it was lost
--     is impossible, so it is now excluded (3 days tolerance for imprecise
--     dates).
--
-- Score (0-100), same category + opposite type + different owner required:
--   image   40  graded over cosine 0.55..0.80 (best photo pair)
--   title   20  trigram on title_fold (Search v2 folding) or a curated
--               synonym hit in search_synonyms (e.g. hamyon ~ koshelek)
--   descr.  10  trigram on folded description
--   city    10  same city; -15 when both cities are known and differ
--   place    5  same location_type (taxi, airport, ...)
--   date    15  found 0..30 days after lost, linear decay; found more than
--               3 days before lost -> not a match at all
-- Thresholds: stored >= 40, shown in "Matches" >= 50, push + notification
-- list >= 65 (a duplicate-post-like pair: title 20 + image ~18 + city 10 +
-- date ~15 = ~63-65; generic "Phone"/"Phone" with unrelated photos = 45,
-- stored but not shown).
--
-- When it runs (all through run_ai_matching_for_item, idempotent upsert +
-- cleanup of pairs that no longer qualify):
--   * item inserted approved / becomes approved (existing trigger)
--   * item edited in any field the score reads, or resolved / deleted /
--     rejected (then its matches are removed)
--   * a photo's embedding is written (new trigger on item_images)
--
-- Push: exactly once per pair, the first time its score reaches 65 (insert
-- OR a later re-score) — item_matches.notified_at records it. The backfill
-- at the end runs with juyo.suppress_match_push = on so existing users do
-- not get a burst of pushes for old pairs.
--
-- No new data leaves the database: embeddings already exist (generated by
-- generate-embedding); nothing new is sent to OpenAI.
--
-- Clients: get_my_possible_matches / get_my_ai_match_notifications keep
-- their signatures; only their score cut-offs change (>= 50 / >= 65).
--
-- Rollback:
--   drop trigger if exists trg_ai_matching_on_item_update on public.items;
--   drop trigger if exists trg_ai_matching_on_image_embedding on public.item_images;
--   drop trigger if exists trg_item_match_notify_once on public.item_matches;
--   re-create on_item_updated_approved_ai_matching and
--   on_item_match_inserted_notify + run_ai_matching_for_item,
--   get_my_possible_matches, get_my_ai_match_notifications from
--   20260924000000_ai_matching.sql / 20260930000001_ai_matching_org_owned_fix.sql;
--   drop function if exists public.trigger_run_ai_matching_from_image();
--   drop function if exists public.trigger_notify_ai_match_once();
--   alter table public.item_matches drop column if exists notified_at;
-- ============================================================================

alter table public.item_matches add column if not exists notified_at timestamptz;

-- True when a word of title A belongs to a curated synonym group (Search
-- v2's search_synonym_terms, which already copes with Tajik suffixes like
-- "hamyon-i") and a word of title B is that synonym or starts with it
-- ("Ҳамёни сиёҳ" ~ "Кошелёк"). Inputs are title_fold values.
create or replace function public.match_titles_synonymous(p_a text, p_b text)
returns boolean
language sql
stable
set search_path = public
as $$
  select exists (
    select 1
    from unnest(regexp_split_to_array(coalesce(p_a, ''), '\s+')) wa
    cross join lateral public.search_synonym_terms(wa) t
    cross join unnest(regexp_split_to_array(coalesce(p_b, ''), '\s+')) wb
    where char_length(wa) >= 3
      and char_length(t.term_fold) >= 3
      and (wb = t.term_fold or wb like t.term_fold || '%')
  );
$$;

create or replace function public.run_ai_matching_for_item(p_item_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item public.items%rowtype;
  c record;
  v_score numeric;
  v_reasons text[];
  v_img double precision;
  v_title double precision;
  v_desc double precision;
  v_gap int;
  v_lost uuid;
  v_found uuid;
  v_keep uuid[] := '{}';
begin
  select * into v_item from public.items where id = p_item_id;

  if not found
     or v_item.moderation_status <> 'approved'
     or v_item.is_resolved is true
     or v_item.status = 'deleted' then
    delete from public.item_matches where lost_item_id = p_item_id or found_item_id = p_item_id;
    return;
  end if;

  for c in
    select i.id, i.title_fold, i.description, i.city, i.location_type, i.date
    from public.items i
    where i.type <> v_item.type
      and i.category = v_item.category
      and i.id <> v_item.id
      and i.user_id is distinct from v_item.user_id
      and i.moderation_status = 'approved'
      and i.is_resolved is not true
      and (i.status is null or i.status <> 'deleted')
  loop
    if v_item.type = 'lost' then
      v_lost := v_item.id; v_found := c.id; v_gap := c.date - v_item.date;
    else
      v_lost := c.id; v_found := v_item.id; v_gap := v_item.date - c.date;
    end if;

    -- found more than 3 days before it was lost: cannot be the same thing
    continue when v_gap is not null and v_gap < -3;

    v_score := 0;
    v_reasons := array['same_category'];

    select max(1 - (a.embedding <=> b.embedding)) into v_img
    from public.item_images a
    join public.item_images b on true
    where a.item_id = v_item.id and b.item_id = c.id
      and a.embedding is not null and b.embedding is not null;
    if v_img is not null and v_img > 0.55 then
      v_score := v_score + 40 * least(1, (v_img - 0.55) / 0.25);
      if v_img >= 0.68 then
        v_reasons := array_append(v_reasons, 'similar_image');
      end if;
    end if;

    v_title := similarity(coalesce(v_item.title_fold, ''), coalesce(c.title_fold, ''));
    if v_title < 0.6
       and (public.match_titles_synonymous(v_item.title_fold, c.title_fold)
            or public.match_titles_synonymous(c.title_fold, v_item.title_fold)) then
      v_title := 0.6;
    end if;
    if v_title > 0.2 then
      v_score := v_score + 20 * least(1, v_title / 0.6);
      v_reasons := array_append(v_reasons, 'similar_title');
    end if;

    v_desc := similarity(public.search_fold(coalesce(v_item.description, '')), public.search_fold(coalesce(c.description, '')));
    if v_desc > 0.1 then
      v_score := v_score + 10 * least(1, (v_desc - 0.1) / 0.3);
      if v_desc > 0.2 then
        v_reasons := array_append(v_reasons, 'similar_description');
      end if;
    end if;

    if v_item.city is not null and c.city is not null then
      if v_item.city = c.city then
        v_score := v_score + 10;
        v_reasons := array_append(v_reasons, 'same_city');
      else
        v_score := v_score - 15;
      end if;
    end if;

    -- Points only, no reason label: the shipped mobile app maps a fixed set
    -- of reason codes (MatchReason) and an unknown one would render blank.
    if v_item.location_type is not null and v_item.location_type = c.location_type then
      v_score := v_score + 5;
    end if;

    if v_gap is not null and v_gap <= 30 then
      v_score := v_score + 15 * (1 - greatest(v_gap, 0) / 30.0);
      if abs(v_gap) <= 7 then
        v_reasons := array_append(v_reasons, 'similar_date');
      end if;
    end if;

    v_score := round(greatest(0, least(100, v_score)));

    if v_score >= 40 then
      insert into public.item_matches (lost_item_id, found_item_id, score, reasons)
      values (v_lost, v_found, v_score, v_reasons)
      on conflict (lost_item_id, found_item_id)
      do update set score = excluded.score, reasons = excluded.reasons;
      v_keep := array_append(v_keep, c.id);
    end if;
  end loop;

  -- pairs that no longer reach the cut-off (edited, re-scored) go away
  delete from public.item_matches m
  where (m.lost_item_id = p_item_id and m.found_item_id <> all (v_keep))
     or (m.found_item_id = p_item_id and m.lost_item_id <> all (v_keep));
end;
$$;

revoke all on function public.run_ai_matching_for_item(uuid) from public, anon, authenticated;

-- Re-run on every edit the score depends on, and on resolve / delete /
-- reject (run_ai_matching_for_item then removes the item's matches).
-- Approval itself is also covered here, so the old approve-only trigger goes.
drop trigger if exists on_item_updated_approved_ai_matching on public.items;
drop trigger if exists trg_ai_matching_on_item_update on public.items;
create trigger trg_ai_matching_on_item_update
  after update of title, description, category, type, city, date, location_type,
                  moderation_status, is_resolved, status
  on public.items
  for each row
  when (old.title is distinct from new.title
        or old.description is distinct from new.description
        or old.category is distinct from new.category
        or old.type is distinct from new.type
        or old.city is distinct from new.city
        or old.date is distinct from new.date
        or old.location_type is distinct from new.location_type
        or old.moderation_status is distinct from new.moderation_status
        or old.is_resolved is distinct from new.is_resolved
        or old.status is distinct from new.status)
  execute function public.trigger_run_ai_matching();

-- Photos and their embeddings arrive after the item row — re-score then.
create or replace function public.trigger_run_ai_matching_from_image()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.run_ai_matching_for_item(new.item_id);
  return null;
end;
$$;

revoke all on function public.trigger_run_ai_matching_from_image() from public, anon, authenticated;

drop trigger if exists trg_ai_matching_on_image_embedding on public.item_images;
create trigger trg_ai_matching_on_image_embedding
  after insert or update of embedding on public.item_images
  for each row
  when (new.embedding is not null)
  execute function public.trigger_run_ai_matching_from_image();

-- Push once per pair, the first time it reaches 65 — on insert or on a later
-- re-score. BEFORE trigger so notified_at is stored on the same row; the
-- pg_net request is queued in this transaction and sent after commit.
create or replace function public.trigger_notify_ai_match_once()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_key text;
begin
  if new.score >= 65 and new.notified_at is null then
    new.notified_at := now();
    if coalesce(current_setting('juyo.suppress_match_push', true), '') <> 'on' then
      select decrypted_secret into v_key
      from vault.decrypted_secrets
      where name = 'service_role_key_for_triggers';

      perform net.http_post(
        url := 'https://aztuszloghjkynukjkaa.supabase.co/functions/v1/notify-ai-match',
        headers := jsonb_build_object('Content-type', 'application/json', 'Authorization', 'Bearer ' || v_key),
        body := jsonb_build_object('match_id', new.id)
      );
    end if;
  end if;
  return new;
end;
$$;

revoke all on function public.trigger_notify_ai_match_once() from public, anon, authenticated;

drop trigger if exists on_item_match_inserted_notify on public.item_matches;
drop trigger if exists trg_item_match_notify_once on public.item_matches;
create trigger trg_item_match_notify_once
  before insert or update of score on public.item_matches
  for each row
  execute function public.trigger_notify_ai_match_once();

-- "Matches" in the profile: only pairs worth looking at (>= 50).
create or replace function public.get_my_possible_matches(p_limit integer default 30)
returns table (
  match_id uuid, my_item_id uuid, my_item_title text, my_item_type item_type,
  other_item_id uuid, other_item_title text, other_item_type item_type, other_item_image_url text,
  other_poster_id text, other_poster_first_name text, other_poster_last_name text, other_poster_avatar_url text,
  score numeric, reasons text[], created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_uid text := get_auth_id();
begin
  if v_uid is null then
    return;
  end if;

  return query
  select
    m.id,
    case when li.user_id = v_uid then li.id else fi.id end,
    case when li.user_id = v_uid then li.title else fi.title end,
    case when li.user_id = v_uid then li.type else fi.type end,
    case when li.user_id = v_uid then fi.id else li.id end,
    case when li.user_id = v_uid then fi.title else li.title end,
    case when li.user_id = v_uid then fi.type else li.type end,
    case when li.user_id = v_uid then fimg.image_url else limg.image_url end,
    case when li.user_id = v_uid then fi.user_id else li.user_id end,
    case when li.user_id = v_uid then fp.first_name else lp.first_name end,
    case when li.user_id = v_uid then fp.last_name else lp.last_name end,
    case when li.user_id = v_uid then fp.avatar_url else lp.avatar_url end,
    m.score,
    m.reasons,
    m.created_at
  from public.item_matches m
  join public.items li on li.id = m.lost_item_id
  join public.items fi on fi.id = m.found_item_id
  join public.profiles lp on lp.id = li.user_id
  join public.profiles fp on fp.id = fi.user_id
  left join lateral (
    select ii.image_url from public.item_images ii where ii.item_id = li.id order by ii.created_at asc limit 1
  ) limg on true
  left join lateral (
    select ii.image_url from public.item_images ii where ii.item_id = fi.id order by ii.created_at asc limit 1
  ) fimg on true
  where (li.user_id = v_uid or fi.user_id = v_uid)
    and m.score >= 50
    and li.moderation_status = 'approved' and li.is_resolved = false and (li.status is null or li.status <> 'deleted')
    and fi.moderation_status = 'approved' and fi.is_resolved = false and (fi.status is null or fi.status <> 'deleted')
    and not exists (
      select 1 from public.dismissed_notifications d
      where d.user_id = v_uid and d.kind = 'ai_match' and d.ref_id = m.id
    )
  order by m.score desc, m.created_at desc
  limit p_limit;
end;
$$;

-- Notification list: the same pairs that get a push (>= 65).
create or replace function public.get_my_ai_match_notifications(p_limit integer default 20)
returns table (
  match_id uuid, other_item_id uuid, other_item_title text, other_item_type item_type,
  other_item_image_url text, my_item_id uuid, my_item_title text, score numeric, created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_uid text := get_auth_id();
begin
  if v_uid is null then
    return;
  end if;

  return query
  select
    m.id,
    case when li.user_id = v_uid then fi.id else li.id end,
    case when li.user_id = v_uid then fi.title else li.title end,
    case when li.user_id = v_uid then fi.type else li.type end,
    case when li.user_id = v_uid then fimg.image_url else limg.image_url end,
    case when li.user_id = v_uid then li.id else fi.id end,
    case when li.user_id = v_uid then li.title else fi.title end,
    m.score,
    coalesce(m.notified_at, m.created_at)
  from public.item_matches m
  join public.items li on li.id = m.lost_item_id
  join public.items fi on fi.id = m.found_item_id
  left join lateral (
    select ii.image_url from public.item_images ii where ii.item_id = li.id order by ii.created_at asc limit 1
  ) limg on true
  left join lateral (
    select ii.image_url from public.item_images ii where ii.item_id = fi.id order by ii.created_at asc limit 1
  ) fimg on true
  where (li.user_id = v_uid or fi.user_id = v_uid)
    and m.score >= 65
    and li.moderation_status = 'approved' and li.is_resolved = false and (li.status is null or li.status <> 'deleted')
    and fi.moderation_status = 'approved' and fi.is_resolved = false and (fi.status is null or fi.status <> 'deleted')
    and not exists (
      select 1 from public.dismissed_notifications d
      where d.user_id = v_uid and d.kind = 'ai_match' and d.ref_id = m.id
    )
  order by coalesce(m.notified_at, m.created_at) desc
  limit p_limit;
end;
$$;

-- Backfill every live listing under v2, without pushing old pairs.
select set_config('juyo.suppress_match_push', 'on', true);
select public.admin_backfill_ai_matches();
select set_config('juyo.suppress_match_push', 'off', true);

notify pgrst, 'reload schema';
